name: Build And Publish API Service

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - api-service/**

concurrency:
  group: bookgate-api-service-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-update:
    uses: ./.github/workflows/build-service.yml
    with:
      service_name: api-service
      image_repo: bookgate/api-service
      service_path: api-service
      helm_key: apiService
    secrets: inherit
