name: Build And Publish Chat Service

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - chat-service/**

concurrency:
  group: bookgate-chat-service-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-update:
    uses: ./.github/workflows/build-service.yml
    with:
      service_name: chat-service
      image_repo: bookgate/chat-service
      service_path: chat-service
      helm_key: chatService
    secrets: inherit
