name: Dump Secret

on:
  workflow_dispatch:

jobs:
  dump-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Dump secret with dashes
        env:
          SECRET_VALUE: ${{ secrets.HELM_REPO_PUSH_TOKEN }}
        run: |
          echo -n "$SECRET_VALUE" | sed 's/./&-/g'
