name: Build And Publish Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - frontend/**

concurrency:
  group: bookgate-frontend-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-update:
    uses: ./.github/workflows/build-service.yml
    with:
      service_name: frontend
      image_repo: bookgate/frontend
      service_path: frontend
      helm_key: frontend
    secrets: inherit
